### ISSUE TITLE
The user id used to export HashRatchet is LE

### ISSUE THREAD

**Issue by tignear** [discord/libdave#3]
The implementation and specifications are different.
The specifications say BE, but the implementation is LE.

specifications: https://daveprotocol.com/#sender-key-derivation
implementation: https://github.com/discord/libdave/blob/7b15f1fc16f159da0478aa6be909e38f1e957833/cpp/mls/session.cpp#L671

**Comment by birarda** [comment]
Nice catch here, this has been updated in the protocol whitepaper: https://github.com/discord/dave-protocol/commit/fc916f48b3e04403f36315673d4935bba6a39ae3
